from setuptools import find_packages, setup

setup(
    name="djangoStorageAuth",
    version="0.1.0",
    author="Eyob",
    author_email="eyobabdellasharo@gmail.com",
    description="Django integration for Google Drive and Microsoft 365 with OAuth and file operations.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/EyobAbdella/djangoStorageAuth",
    packages=find_packages(where="."),
    include_package_data=True,
    install_requires=[
        "django>=5.2",
        "django-encrypted-model-fields>=0.6.5",
        "djangorestframework>=3.16.0",
        "djangorestframework-simplejwt>=5.4.0",
        "oauthlib>=3.2.2",
        "pyjwt>=2.10.1",
        "python-dotenv>=1.1.0",
        "requests>=2.32.3",
        "google-auth",
        "google-auth-oauthlib",
        "google-auth-httplib2",
        "google-api-python-client",

    ],
    classifiers=[
        "Framework :: Django",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",
)
